<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    $products = [
      [
        'name' => "Nike Air Max 1/97 'Sean Wotherspoon'",
        'slug' => "nike-air-max-1-97-sean-wotherspoon",
        'description' => "Limitovaná edícia vytvorená v spolupráci so Seanom Wotherspoonom, ktorá spája ikonické prvky Air Max 1 a Air Max 97. Charakteristická farebným kordovým zvrškom a retro atmosférou, patrí medzi najvyhľadávanejšie modely u zberateľov.",
        'manufacturer' => "Nike",
        'gender' => "Unisex",
        'color' => "yellow",
        'type' => "Sneaker",
        'price' => 899.99,
        'isSale' => true,
        'salePrice' => 799.99,
        'release_date' => '2018-03-26',
      ],
      [
        'name' => "Reebok Question Mid 'Packer Shoes Take on Blacktop'",
        'slug' => "reebok-question-mid-packer-blacktop",
        'description' => "Exkluzívna spolupráca s Packer Shoes vnesie do klasickej basketbalovej siluety streetový nádych. Prémiové materiály, špeciálne farby a speckled podrážka z nej robia unikátny pár pre milovníkov retra.",
        'manufacturer' => "Reebok",
        'gender' => "Unisex",
        'color' => "black",
        'type' => "Sneaker",
        'price' => 160.99,
        'isSale' => false,
        'salePrice' => 0.00,
        'release_date' => '2019-09-01',
      ],
      [
        'name' => "Nike Joyride Run Flyknit",
        'slug' => "nike-joyride-run-flyknit",
        'description' => "Bežecká teniska s inovatívnym tlmením Joyride, ktorá ponúka tisícky TPE guľôčok pre adaptívne pohodlie. Flyknit zvršok zabezpečuje výbornú priedušnosť a pevné obopnutie chodidla.",
        'manufacturer' => "Nike",
        'gender' => "Unisex",
        'color' => "gray",
        'type' => "Running Shoe",
        'price' => 180.99,
        'isSale' => false,
        'salePrice' => 0.00,
        'release_date' => '2019-07-22',
      ],
      [
        'name' => "Air Jordan 4 Retro 'Midnight Navy'",
        'slug' => "air-jordan-4-retro-midnight-navy",
        'description' => "Elegantná a nadčasová silueta Air Jordan 4 v odtieni Midnight Navy. Prémiový semiš, sieťované panely a viditeľná Air jednotka vytvárajú nezameniteľný štýl pre milovníkov klasiky.",
        'manufacturer' => "Nike",
        'gender' => "Unisex",
        'color' => "blue",
        'type' => "Sneaker",
        'price' => 210.99,
        'isSale' => false,
        'salePrice' => 0.00,
        'release_date' => '2020-11-28',
      ],
      [
        'name' => "Air Jordan 1 Retro High OG 'Travis Scott'",
        'slug' => "air-jordan-1-retro-high-og-travis-scott",
        'description' => "Ikonická teniska, ktorá spája štýl, exkluzivitu a jedinečný dizajn. Tento model, vytvorený v spolupráci so svetoznámym rapperom Travisom Scottom, vyniká prémiovým koženým a semišovým zvrškom, charakteristickým otočeným Swoosh logom a skrytou kapsičkou na bočnej strane.",
        'manufacturer' => "Nike",
        'gender' => "Unisex",
        'color' => "brown",
        'type' => "Sneaker",
        'price' => 1800.00,
        'isSale' => true,
        'salePrice' => 1689.99,
        'release_date' => '2019-05-11',
      ],
      [
        'name' => "Union LA x Air Jordan 4 'Guava Ice'",
        'slug' => "union-la-air-jordan-4-guava-ice",
        'description' => "Výsledok spolupráce Union LA a Nike prináša dekonštruovaný vzhľad, jemné pastelové farby a unikátne prvky ako preklopený jazyk a vintage podrážka. Model, ktorý zaujme každého sneaker entuziastu.",
        'manufacturer' => "Nike",
        'gender' => "Women",
        'color' => "white",
        'type' => "Sneaker",
        'price' => 250.99,
        'isSale' => false,
        'salePrice' => 0.00,
        'release_date' => '2020-06-25',
      ],
      [
        'name' => "Neckface x Nike SB Dunk Low",
        'slug' => "neckface-nike-sb-dunk-low",
        'description' => "Šialený a rebelský dizajn s podpisom umelca Neckface. Graffiti nášivky a výšivky na čiernom semiši dodávajú teniske neprehliadnuteľný charakter. Ideálna voľba pre tých, ktorí hľadajú originalitu.",
        'manufacturer' => "Nike",
        'gender' => "Unisex",
        'color' => "black",
        'type' => "Sneaker",
        'price' => 120.99,
        'isSale' => false,
        'salePrice' => 0.00,
        'release_date' => '2020-03-01',
      ],
      [
        'name' => "Nike Ja 1 'Hunger'",
        'slug' => "nike-ja-1-hunger",
        'description' => "Basketbalová silueta stvorená pre Ja Moranta s agresívnym dizajnom, graffiti prvkami a priedušným zvrškom. Vďaka technológii Zoom Air ponúka maximálnu výbušnosť a komfort na ihrisku.",
        'manufacturer' => "Nike",
        'gender' => "Women",
        'color' => "pink",
        'type' => "Sneaker",
        'price' => 110.99,
        'isSale' => false,
        'salePrice' => 0.00,
        'release_date' => '2022-07-15',
      ],
      [
        'name' => "Air Jordan 4 'Bred' (2019)",
        'slug' => "air-jordan-4-bred-2019",
        'description' => "Reedícia legendárneho modelu z roku 1989, známa ako 'Bred'. Čierna koža, červené akcenty a ikonické prvky Jordan 4 vytvárajú nesmrteľný vzhľad pre každého sneakerhead-a.",
        'manufacturer' => "Nike",
        'gender' => "Unisex",
        'color' => "black",
        'type' => "Sneaker",
        'price' => 200.99,
        'isSale' => false,
        'salePrice' => 0.00,
        'release_date' => '2019-05-01',
      ],
      [
        'name' => "Air Jordan 1 High 'Court Purple'",
        'slug' => "air-jordan-1-high-court-purple",
        'description' => "Svieži fialový variant klasickej Air Jordan 1. Prémiová koža, vysoký strih a nadčasový dizajn robia z tejto tenisky štýlový kúsok na každý deň.",
        'manufacturer' => "Nike",
        'gender' => "Unisex",
        'color' => "purple",
        'type' => "Sneaker",
        'price' => 180.99,
        'isSale' => false,
        'salePrice' => 0.00,
        'release_date' => '2020-02-14',
      ],
      [
        'name' => "New Balance 9060 'Ivory Cream'",
        'slug' => "new-balance-9060-ivory-cream",
        'description' => "Model inšpirovaný retro estetikou 90. rokov v kombinácii s moderným dizajnom. Prémiový semiš, neutrálne farby a inovatívne tlmenie ABZORB robia z tejto tenisky dokonalého každodenného spoločníka.",
        'manufacturer' => "New Balance",
        'gender' => "Women",
        'color' => "white",
        'type' => "Sneaker",
        'price' => 150.99,
        'isSale' => false,
        'salePrice' => 0.00,
        'release_date' => '2021-04-10',
      ],
      [
        'name' => "Adidas Yeezy Boost 350 V2 'Zebra'",
        'slug' => "adidas-yeezy-boost-350-v2-zebra",
        'description' => "Kultový model z dielne Kanyeho Westa a Adidasu. Zebra vzor na zvršku z Primeknit materiálu a ikonická technológia Boost poskytujú výnimočný vzhľad a pohodlie.",
        'manufacturer' => "Adidas",
        'gender' => "Women",
        'color' => "white",
        'type' => "Sneaker",
        'price' => 220.99,
        'isSale' => false,
        'salePrice' => 0.00,
        'release_date' => '2017-02-25',
      ],
      [
        'name' => "Nike Dunk Low 'USC'",
        'slug' => "nike-dunk-low-usc",
        'description' => "Nízky profil, červená a žltá kombinácia – pocta univerzitnému tímu USC. Prémiová koža a ikonický dizajn Dunk Low z nej robia must-have pre basketbalových fanúšikov.",
        'manufacturer' => "Nike",
        'gender' => "Unisex",
        'color' => "red",
        'type' => "Sneaker",
        'price' => 110.99,
        'isSale' => false,
        'salePrice' => 0.00,
        'release_date' => '2020-11-05',
      ],
      [
        'name' => "Nike Air Force 1 Low 'Chicago'",
        'slug' => "nike-air-force-1-low-chicago",
        'description' => "Červená, biela a čierna farba inšpirovaná tímom Chicago Bulls. Air Force 1 Low spája basketbalové dedičstvo s pouličným štýlom, vďaka čomu patrí medzi najobľúbenejšie modely vôbec.",
        'manufacturer' => "Nike",
        'gender' => "Unisex",
        'color' => "red",
        'type' => "Sneaker",
        'price' => 130.99,
        'isSale' => false,
        'salePrice' => 0.00,
        'release_date' => '2019-04-22',
      ],
      [
        "name" => "Nike Air Max 97 'Silver Bullet'",
        "slug" => "nike-air-max-97-silver-bullet",
        "description" => "'Silver Bullet' je klasická verzia Air Max 97 s reflexným strieborným zvrškom a červenými akcentmi, ktorá ponúka štýl aj pohodlie.",
        "manufacturer" => "Nike",
        "gender" => "Unisex",
        "color" => "silver/red",
        "type" => "Sneaker",
        "price" => 179.99,
        "isSale" => true,
        "salePrice" => 159.99,
        "release_date" => "2017-11-01"
      ],
      [
        "name" => "Adidas Ultra Boost 2020 'White'",
        "slug" => "adidas-ultra-boost-2020-white",
        "description" => "Ultra Boost 2020 s Primeknit zvrškom a reakčným Boost tlmením ponúka pohodlný a tesný strih, ideálny pre bežcov.",
        "manufacturer" => "Adidas",
        "gender" => "Women",
        "color" => "white",
        "type" => "Running Shoe",
        "price" => 179.99,
        "isSale" => true,
        "salePrice" => 159.99,
        "release_date" => "2020-01-01"
      ],
      [
        "name" => "Puma RS-X 'Re-Invention'",
        "slug" => "puma-rs-x-re-invention",
        "description" => "RS-X 'Re-Invention' kombinuje retro dizajn s modernými prvkami, pričom ponúka výrazné farby a robustnú siluetu.",
        "manufacturer" => "Puma",
        "gender" => "Unisex",
        "color" => "multicolor",
        "type" => "Sneaker",
        "price" => 129.99,
        "isSale" => true,
        "salePrice" => 109.99,
        "release_date" => "2019-10-15"
      ],
      [
        "name" => "Asics Gel-Lyte III 'OG'",
        "slug" => "asics-gel-lyte-iii-og",
        "description" => "Gel-Lyte III 'OG' je vybavený rozdeleným jazykom a Gel tlmením, ktoré poskytuje pohodlný strih a klasický dizajn.",
        "manufacturer" => "Asics",
        "gender" => "Unisex",
        "color" => "grey/white",
        "type" => "Sneaker",
        "price" => 109.99,
        "isSale" => true,
        "salePrice" => 89.99,
        "release_date" => "1990-01-01"
      ],
      [
        "name" => "New Balance 574 'Classic'",
        "slug" => "new-balance-574-classic",
        "description" => "574 'Classic' kombinuje zvršok zo semišu a sieťoviny s ENCAP tlmením, čo poskytuje nadčasový vzhľad a pohodlie.",
        "manufacturer" => "New Balance",
        "gender" => "Unisex",
        "color" => "navy/white",
        "type" => "Sneaker",
        "price" => 89.99,
        "isSale" => true,
        "salePrice" => 69.99,
        "release_date" => "1988-01-01"
      ],
      [
        "name" => "Converse Chuck Taylor All Star 'Black'",
        "slug" => "converse-chuck-taylor-all-star-black",
        "description" => "Chuck Taylor All Star 'Black' ponúka klasický plátený zvršok a gumovú podrážku, čo poskytuje univerzálny a ikonický štýl.",
        "manufacturer" => "Converse",
        "gender" => "Unisex",
        "color" => "black",
        "type" => "Sneaker",
        "price" => 59.99,
        "isSale" => true,
        "salePrice" => 49.99,
        "release_date" => "1917-01-01"
      ]
    ];


    foreach ($products as $product) {
      DB::table('products')->insert([
        ...$product,
        'created_at' => now(),
        'updated_at' => now()
      ]);
    }
  }
}
